### ISSUE TITLE
咨询一下作业分数的问题

### ISSUE THREAD

**Issue by Frostmoune** [multicoresysu/multicore_sysu_slides#11]
学号16337188，想知道为什么openmp部分的正确性得分是30，同时想知道为什么cuda部分性能分是0。助教如果有空的话能否告知，谢谢。邮箱为a59135996@qq.com

**Comment by williamSYSU** [comment]
感谢提醒，openmp部分的正确性得分已经更正了。但是cuda的性能分为0，是因为我们测试的s为1000，运行你的程序时会报错，你可以在集群上测试一下。



------------------ 原始邮件 ------------------
发件人: "Frostmoune"<notifications@github.com>; 
发送时间: 2019年5月16日(星期四) 下午3:32
收件人: "multicoresysu/multicore_sysu_slides"<multicore_sysu_slides@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [multicoresysu/multicore_sysu_slides] 咨询一下作业分数的问题 (#11)




学号16337188，想知道为什么openmp部分的正确性得分是30，同时想知道为什么cuda部分性能分是0。助教如果有空的话能否告知，谢谢。邮箱为a59135996@qq.com
 
&mdash;

**Comment by Frostmoune** [comment]
> 感谢提醒，openmp部分的正确性得分已经更正了。但是cuda的性能分为0，是因为我们测试的s为1000，运行你的程序时会报错，你可以在集群上测试一下。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Frostmoune"<notifications@github.com>; 发送时间: 2019年5月16日(星期四) 下午3:32 收件人: "multicoresysu/multicore_sysu_slides"<multicore_sysu_slides@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [multicoresysu/multicore_sysu_slides] 咨询一下作业分数的问题 (#11) 学号16337188，想知道为什么openmp部分的正确性得分是30，同时想知道为什么cuda部分性能分是0。助教如果有空的话能否告知，谢谢。邮箱为a59135996@qq.com &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

我能问一下具体是什么错误吗？我这边是可以运行的，是运行出来的结果出错了吗？

**Comment by williamSYSU** [comment]
第一次测试的时候会报错，应该是当时显存不够了所以会报错，我已经帮你把性能分重新加上去了。
