### ISSUE TITLE
作业一作业上没有我的成绩

### ISSUE THREAD

**Issue by CleverFat** [multicoresysu/multicore_sysu_slides#12]
ta您好，我是金柏汇，学号16337107，在计分板上没有看到自己的成绩=-=

**Comment by CleverFat** [comment]
and之前清空过一次发件记录现在没有发送记录了

**Comment by williamSYSU** [comment]
邮箱中没有收到你的邮件，请重新发一份作业到作业邮箱(163邮箱)，并将你之前发送成功的截图发到我的邮箱。




------------------ 原始邮件 ------------------
发件人: "Kim"<notifications@github.com>; 
发送时间: 2019年5月16日(星期四) 晚上10:46
收件人: "multicoresysu/multicore_sysu_sl"<multicore_sysu_slides@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [multicoresysu/multicore_sysu_slides] 作业一作业上没有我的成绩 (#12)




ta您好，我是金柏汇，学号16337107，在计分板上没有看到自己的成绩=-=
 
&mdash;

**Comment by CleverFat** [comment]
TA您好
我是学号16337107的金柏汇，几星期前我使用邮箱清理将收件记录和发件记录都清除了，所以不能够提供之前提交的截图，十分抱歉！不过本地有压缩包打包的时间戳

**Comment by williamSYSU** [comment]
成绩已经更新。
