### ISSUE TITLE
关于作业二答案的问题

### ISSUE THREAD

**Issue by Jhhhha** [multicoresysu/multicore_sysu_slides#15]
助教好，关于作业二的答案，班里的很多同学都算不出您给出的答案，不知道助教方不方便给出样例中的卷积核以及您的padding方式，还有卷积公式。

**Comment by xihuai18** [comment]
同意，我用计算器算出来第一个数应该是171

**Comment by xihuai18** [comment]
![image](https://user-images.githubusercontent.com/23721828/58016353-f96f2180-7b2f-11e9-90c6-16e0add1fec0.png)
![image](https://user-images.githubusercontent.com/23721828/58016412-20c5ee80-7b30-11e9-952f-dae13d18e815.png)
助教你的代码忽略了这个卷积核的大小是6*s+1，而不是2*s+1

**Comment by seiki0901** [comment]
输出到底是两位小数还是六位小数？TA请不要这么随便！
