### ISSUE TITLE
第一次作业成绩文档中没有找到我的成绩

### ISSUE THREAD

**Issue by oqsh** [multicoresysu/multicore_sysu_slides#16]
老师您好，我的学号是16337200，对应md5哈希值为eda5200d1a5ec9a474a5e6599c49436b。第一次作业成绩单中没有找到我的成绩。以下是我4月8日提交作业的邮件截图。麻烦您让助教师兄检查一下是不是忘记批改了我的作业？【我刚刚也发送我的作业和截图到作业邮箱MulticoreSYSU@163.com了】
![image](https://user-images.githubusercontent.com/30433920/57979688-f272e100-7a53-11e9-8df9-59611eb6978a.png)

**Comment by williamSYSU** [comment]
成绩已经更新，请查看。
