### ISSUE TITLE
第一次作业没有我的成绩

### ISSUE THREAD

**Issue by violator0107** [multicoresysu/multicore_sysu_slides#17]
老师你好，我叫黄维哲，我的学号是16337096，MD5加密的HASH值是c94f554a2121ee7fb239f1fadcc398f3，我在第一次作业的表格上找不到我的成绩，不知道是ta忘记加上去还是没收到我的邮件

![image](https://user-images.githubusercontent.com/50646645/58004796-a2108780-7b16-11e9-991e-c5cca497ba34.png)

**Comment by Dznan** [comment]
我也查不到我的学号，16337049

**Comment by Dznan** [comment]
![image](https://user-images.githubusercontent.com/21004648/58106407-a3c37380-7c1a-11e9-8207-159191f090ad.png)

**Comment by williamSYSU** [comment]
成绩已经更新，请查看。
