### ISSUE TITLE
作业一OpenMP编译失败问题

### ISSUE THREAD

**Issue by ghost** [multicoresysu/multicore_sysu_slides#19]
<img width="443" alt="make" src="https://user-images.githubusercontent.com/28523660/58092076-cc894000-7bfd-11e9-8876-9fb568e75611.PNG">
师兄，我自己用提交的Makefile文件和OpenMP.c在集群上是可以编译运行的，不清楚为什么成绩里指出“OpenMP编译失败”？
我的学号是16337153

**Comment by CleverFat** [comment]
数学库是你自己编译的么？可能是-lm的锅

**Comment by williamSYSU** [comment]
我加了-lm参数后重新编译程序运算正确，成绩已经更新。
