### ISSUE TITLE
作业1性能评测方法的问题

### ISSUE THREAD

**Issue by sunyiyan123** [multicoresysu/multicore_sysu_slides#22]
在excel表格中我的成绩是22ms，猜测TA使用nvprof进行评测，但是我自己评测时高斯函数计算只用了200us，其中GPUactivity总共是22ms，包括了设备内存拷贝到主机内存的时间。

但是参考并评测了另一位成绩为1ms的同学的代码，同样使用nvprof评测。GPUactivity总共是90多ms，其中高斯函数计算是1ms，内存拷贝90ms。

请问能否麻烦TA公布性能评测方法以及对正确性进行核实，谢谢TA！

**Comment by williamSYSU** [comment]
我们的确是使用nvprof进行评测，也是计算高斯函数的运行时间，请提供一下你的学号，我把评测结果截图给你看。

**Comment by sunyiyan123** [comment]
16337216，谢谢TA！

**Comment by williamSYSU** [comment]
不好意思，我们重新测试过了，你的性能时间是0.1737ms，可能是另一个TA一开始算错了，你的成绩已经更新。

**Comment by sunyiyan123** [comment]
收到
