### ISSUE TITLE
咨询作业二性能评估方法

### ISSUE THREAD

**Issue by hongwen000** [multicoresysu/multicore_sysu_slides#23]
请问作业二中将如何评估程序性能，是否会将利用作业一中的代码计算高斯卷积核的时间也算入在内？还是仅计算名为`kernel`的核函数的运行时间？

**Comment by sunyiyan123** [comment]
以及s的取值范围

**Comment by rinfx** [comment]
TA你好，请问评价程序性能是使用nvprof吗？如果是的话，是根据哪个指标呢？是根据GPU activities还是也包括API calls？或者说只根据GPU activities中的核函数？
