### ISSUE TITLE
作业2输出样例问题

### ISSUE THREAD

**Issue by rinfx** [multicoresysu/multicore_sysu_slides#24]
TA你好，你给出的data.bin的标准输出与data.bin好像不匹配，是否应该更新data.bin？另外performance_standard.txt这个文件中每一项之间没有用空格隔开。

另外TA应该是用python算出来的结果，但是与同学们用CUDA算出来的很多地方差0.01，这个精度问题很难修改。

另外能否把第一次作业的性能评估使用的s=1000的测试结果给出来？

**Comment by why116600** [comment]
问题已经修正
精度问题，我们评测的误差范围就是0.01
第一次作业的正确性我们用的是s=2，性能评估才用s=1000，数据量较大

**Comment by rinfx** [comment]
已收到，谢谢！




------------------ 原始邮件 ------------------
发件人: "why116600"<notifications@github.com>; 
发送时间: 2019年5月23日(星期四) 晚上9:01
收件人: "multicoresysu/multicore_sysu_slides"<multicore_sysu_slides@noreply.github.com>; 
抄送: "刘晓瑞"<893383980@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [multicoresysu/multicore_sysu_slides] 作业2输出样例问题 (#24)




问题已经修正
 精度问题，我们评测的误差范围就是0.01
 第一次作业的正确性我们用的是s=2，性能评估才用s=1000，数据量较大

**Comment by rinfx** [comment]
我自己写了个评测输出正确性的脚本，读取自己的输出和给的样例答案，发现原本相差0.01的两个数读进去做差后结果的绝对值大于0.01，这应该是编码问题，如下图所示

![image](https://user-images.githubusercontent.com/25995563/58332360-a4077d00-7e6d-11e9-8fae-f647287a3b53.png)

建议评测时得到差以后用round(a-b, 2)来舍入一下。

```python
f1 = open('performance_standard.txt', 'r')
f2 = open('cuda_output.txt', 'r')
f1 = f1.read().split()
f2 = f2.read().split()
flag = True
for i in range(0, len(f1)):
    a = float(f1[i])
    b = float(f2[i])
    if round(a-b,2) > 0.01:
        print(a,b,a-b)
        flag = False
if flag:
    print('The results are right!')
```
