### ISSUE TITLE
作业一“OpenMP源程序为乱码，集群无法正确编译”问题

### ISSUE THREAD

**Issue by oqsh** [multicoresysu/multicore_sysu_slides#25]
师兄你好，我的学号是16337200。
1. 我的openMP源程序是乱码是因为其中带有中文注释（编码方式为GB2312）
2. 关于“集群无法正确编译”的问题：我在集群上面进行了编译运行后发现是正确的，编译运行结果截图如下：
![image](https://user-images.githubusercontent.com/30433920/58366337-550c2700-7f03-11e9-9321-007fe30bf339.png)
希望师兄可以帮忙重新查看一下，谢谢！

**Comment by williamSYSU** [comment]
成绩已经更正，请查看。
