### ISSUE TITLE
关于作业一成绩问题；

### ISSUE THREAD

**Issue by Foollllll** [multicoresysu/multicore_sysu_slides#26]
TA你好，我是16339048武康康，第一次作业由于Makefile文件不正确导致无法编译，并且实验报告没有分数；出成绩后邮件咨询TA实验报告0分问题未得到回复；5月27日重新提交了正确的Makeflie、代码、报告打包文件以及是否做了改动，未得到更新后的成绩；希望TA可以抽空重改一下，谢谢；

**Comment by Foollllll** [comment]
附邮件截图：
![4M4J0FN$YNUCEW}QBZ6BTFD](https://user-images.githubusercontent.com/49099314/59147960-b3252800-8a34-11e9-9eb1-27045f1f1677.png)
![QCD(BP2UHO_KBQT3O@1$7W1](https://user-images.githubusercontent.com/49099314/59147967-cc2dd900-8a34-11e9-8e7c-46b66c5cb482.png)

**Comment by williamSYSU** [comment]
已经重新改了你的作业，但是错误仍然存在。

- OpenMP程序报错
![image](https://user-images.githubusercontent.com/15846067/59276463-e8c64d00-8c90-11e9-967a-b27f6a505efd.png)

- CUDA程序报错
![image](https://user-images.githubusercontent.com/15846067/59276513-072c4880-8c91-11e9-8676-41f15c432ed2.png)

**Comment by Foollllll** [comment]
TA你好，
关于hw1，s = 1000时程序报错的问题，多次尝试修改，但我暂时还没有办法解决；
希望TA可以就目前我的作业的情况给出合适的成绩；
辛苦TA！




------------------ 原始邮件 ------------------
发件人: "WilliamLam"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 晚上9:37
收件人: "multicoresysu/multicore_sysu_slides"<multicore_sysu_slides@noreply.github.com>;
抄送: "1747362251"<1747362251@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [multicoresysu/multicore_sysu_slides] 关于作业一成绩问题； (#26)




已经重新改了你的作业，但是错误仍然存在。
  
 
OpenMP程序报错
 
 
 
 
CUDA程序报错

**Comment by williamSYSU** [comment]
程序无法运行，所以很难给出相应的成绩，如果有问题可以向老师咨询一下这个情况该怎么处理。

**Comment by Foollllll** [comment]
好的，课后我会咨询老师，谢谢TA。
