### ISSUE TITLE
第一次作业重交

### ISSUE THREAD

**Issue by rinfx** [multicoresysu/multicore_sysu_slides#27]
TA你好，我在5.25重新提交过了作业1，已发送邮件，希望TA能够改一下然后更新一下成绩，谢谢！
![image](https://user-images.githubusercontent.com/25995563/59267147-05a45580-8c7c-11e9-8d7f-fc80681cba6c.png)

**Comment by williamSYSU** [comment]
作业成绩已经更新，请查看。
