### ISSUE TITLE
第一次作业重交（解决了原来集群上gcc版本问题）

### ISSUE THREAD

**Issue by AMShek** [multicoresysu/multicore_sysu_slides#28]
TA你好，我之前重交过一次hw1，解决了其中操作系统不兼容的问题，但仍存在gcc版本过高不可以使用集群上nvcc的问题，现已改正此问题。我已将修改后的hw1压缩包发送至作业邮箱，烦请接收批改，谢谢！
![屏幕快照 2019-06-11 下午8 10 18](https://user-images.githubusercontent.com/26130484/59270906-32a93600-8c85-11e9-85da-6a5ef85cc64c.png)

**Comment by williamSYSU** [comment]
你发的邮件里面没有附件，请重新提交。

**Comment by AMShek** [comment]
> 你发的邮件里面没有附件，请重新提交。

抱歉，已补发。

**Comment by williamSYSU** [comment]
成绩已经更新。
