### ISSUE TITLE
第一次作业正确性

### ISSUE THREAD

**Issue by yuosef46** [multicoresysu/multicore_sysu_slides#29]
![image](https://user-images.githubusercontent.com/27205419/59276667-9f83e800-8c13-11e9-90c6-8d8a8bd4a7f4.png)
按图上说我的makefile 的名字不对，我不知道是怎么回事，我在这里能无毛病地跑。我在做第二作业的时候我也同时在改makefile，有可能这个问题导致出这个错。

**Comment by yuosef46** [comment]
学号是16952013

**Comment by williamSYSU** [comment]
成绩已经更新。
