### ISSUE TITLE
第一次作业修改

### ISSUE THREAD

**Issue by Tsengzu** [multicoresysu/multicore_sysu_slides#30]
TA你好，我是学号为16339061的庄钟嵛。我第一次作业因为语言问题无法通过集群上的编译，现已改正，希望TA能够帮我重新批改一下作业。
[图片]

**Comment by Tsengzu** [comment]
![NC6}~J{N$6D2UU9U12%2K6H](https://user-images.githubusercontent.com/34064944/59283094-92f7a200-8c9c-11e9-8b05-cc1cd8623e81.png)

**Comment by williamSYSU** [comment]
成绩已经更新。
