### ISSUE TITLE
第一次作业修改

### ISSUE THREAD

**Issue by JasonChouZZH** [multicoresysu/multicore_sysu_slides#31]
![hw1](https://user-images.githubusercontent.com/41731282/59285307-5b8af480-8ca0-11e9-982c-5af42878f2d2.png)
TA你好，我是周子豪，学号16339060。第一次作业出了问题，已做相应修改，希望你能重新批改一下，谢谢。

**Comment by williamSYSU** [comment]
成绩已经更新。
