### ISSUE TITLE
第一次作业仍未有成绩

### ISSUE THREAD

**Issue by gjh16337068** [multicoresysu/multicore_sysu_slides#32]
![image](https://user-images.githubusercontent.com/25917446/59335745-c2a3ba00-8d2f-11e9-8cef-f0271aea37ff.png)

TA你好，我是郭锦鸿，学号16337068。第一次作业仍未有成绩，已经重发了两次作业邮件了，但至今未有回复或者成绩更新，麻烦TA能检查一下，图为当时交作业的时间证明。

**Comment by williamSYSU** [comment]
成绩已经更新。
