### ISSUE TITLE
第一次作业nvprof疑问

### ISSUE THREAD

**Issue by rinfx** [multicoresysu/multicore_sysu_slides#33]
TA你好，我是16337159 刘晓瑞
最新的成绩excel表格上我的备注是nvprof没有对应核函数时间：
![image](https://user-images.githubusercontent.com/25995563/59414817-de24c880-8df4-11e9-8f49-1c273e26f954.png)

但是我在集群上运行时有核函数的运行时间：
![image](https://user-images.githubusercontent.com/25995563/59414984-3956bb00-8df5-11e9-992c-1835b96f94ff.png)

**Comment by williamSYSU** [comment]
成绩已经更新。
