### ISSUE TITLE
第二次作业核函数命名

### ISSUE THREAD

**Issue by rinfx** [multicoresysu/multicore_sysu_slides#34]
TA你好，我作业2中因为生成卷积核和卷积都用到了核函数，所以两个核函数命名为guass2d_kenal，convolve_kernal。convolve_kernal是卷积运算所用的时间。

很抱歉没有注意到作业2要求核函数命名为kernal，希望TA能够看一下convolve_kernal核函数的运行时间，谢谢

**Comment by williamSYSU** [comment]
作业2的成绩已经更新。
