### ISSUE TITLE
第一次作业修改

### ISSUE THREAD

**Issue by RyanLiu2015** [multicoresysu/multicore_sysu_slides#37]
第一次作业因编码问题无法在集群上运行。已使用正确的方式编码并在2周前重新发送了邮件，目前成绩还未修改。
附邮件发送截图。
![邮件提交记录截图 (1)](https://user-images.githubusercontent.com/25746588/59546908-2a444a00-8f68-11e9-9a8d-e7f3fda3d1ea.jpg)

**Comment by williamSYSU** [comment]
成绩已经更新。
