### ISSUE TITLE
实验1计时的时候要算输出时间么

### ISSUE THREAD

**Issue by CleverFat** [multicoresysu/multicore_sysu_slides#4]

**Comment by williamSYSU** [comment]
自己在调试程序的时候可以输出时间并写在实验报告中，但是在提交作业时需要把输出时间的语句注释掉，以免跟用来验证正确性的结果混在一块儿。
我们在评估程序性能时会另外统计运行时间，这样比较容易比较。

**Comment by CleverFat** [comment]
不好意思让您误会了，我的意思是，输出结果的耗时要算在结果之内么

**Comment by williamSYSU** [comment]
输出结果的耗时不会算在结果里面。请留意GitHub主页的关于作业的通知。

**Comment by CleverFat** [comment]
请问在集群上测试运行的时候是手动将输出注释掉么，还是有其他统计运行时间的方法

**Comment by CleverFat** [comment]
另外可以使用自己安装的其他编译器么
