### ISSUE TITLE
作业2成绩问题

### ISSUE THREAD

**Issue by CleverFat** [multicoresysu/multicore_sysu_slides#41]
ta您好，我的学号是16337107，在评分表中提示我的输出结果全为0，但是我重新测试后输出结果并不是这样的，输出结果不为0且正确
![image](https://user-images.githubusercontent.com/35131727/59559297-6e9e1b80-9036-11e9-8c28-219e522d2806.png)

**Comment by Coxy7** [comment]
TA您好，我的学号是16337258，也出现了评分表显示输出结果为0，但（使用发至邮箱的代码）重新测试输出正常的情况。
![image](https://user-images.githubusercontent.com/22617682/59562463-bedda380-905f-11e9-8b87-0207d2cbfc92.png)

**Comment by williamSYSU** [comment]
@CleverFat 
输出结果全为0。原因：程序输入参数应有两个（data.bin和卷积核大小s），但是你的程序卷积核大小s的参数需要进入程序后才能输入，请重新修改代码后提交，分数会相应在复查的基础上扣5分。

@Carlxiao 
输出结果全为0。原因：虽然程序在20\*20的样例数据中运行正确，但是测试数据为重新生成的100\*100数据，程序输出结果为0。请重新修改代码后提交，分数会相应在复查的基础上扣5分。

**Comment by Coxy7** [comment]
TA您好，我的学号是16337258，我于6月22日针对本issue的问题提交了修改后的代码（见下图），但目前（7月22日）最新的成绩表中还未更新成绩，麻烦TA登记一下，谢谢！
![image](https://user-images.githubusercontent.com/22617682/61637894-ecef7c80-acca-11e9-9a10-b6b3e73a1939.png)

**Comment by williamSYSU** [comment]
抱歉，我更新一下。

**Comment by williamSYSU** [comment]
@Carlxiao 成绩已经更新。
