### ISSUE TITLE
hw1成绩更新疑问_

### ISSUE THREAD

**Issue by hisproc** [multicoresysu/multicore_sysu_slides#42]
TA您好，我是谢江钊，学号16337259，今天的成绩更新后我的分数没有得到加上去，备注是程序运行结果错误，我已经在集群上测试，希望您能够回复我具体的原因是什么
![Snipaste_2019-06-16_14-01-34](https://user-images.githubusercontent.com/23616139/59560269-bc6c5100-9041-11e9-92a9-9d1c0762216d.png)
我的代码在集群上能够正常解压和编译,
我另外创建了out_std.py用于Python生成标准结果和cmp.py用于对比生成结果，结果数据是正确的
![Snipaste_2019-06-16_14-14-06](https://user-images.githubusercontent.com/23616139/59560445-ad3ad280-9044-11e9-8b8c-de7bae6c0aa9.png)
因此我想到也许是您这边的脚本要求直接输出结果而不是文件，因此我改变了输出结果到终端而不是文件。
希望您能够重新帮我测试一次代码，这门课对我非常重要，希望能够得到相应的成绩，再次麻烦您批改了，谢谢~
相关代码已经重新压缩发送到Multicode邮箱，没有改动函数等内容，只是把之前注释的输出函数恢复回来，谢谢

**Comment by williamSYSU** [comment]
成绩已经更新。
