### ISSUE TITLE
关于作业二的运行效率

### ISSUE THREAD

**Issue by ghost** [multicoresysu/multicore_sysu_slides#43]
TA您好，我在实验报告里已经讨论过线程数设置的情况，但是提交的作业二代码中，线程数忘了修改成合适的大小，导致运算效率比较低。
想问下线程数能不能修改成合适的大小，再测试一次？ 16337153 凌笑铃
实验报告：
<img width="624" alt="a" src="https://user-images.githubusercontent.com/28523660/59561224-46bbb180-9050-11e9-847f-9f043f783b60.PNG">
提交代码参数设置：
<img width="131" alt="c" src="https://user-images.githubusercontent.com/28523660/59561242-87b3c600-9050-11e9-9d43-307efe8c98f0.PNG">

**Comment by williamSYSU** [comment]
已经修改参数并更新成绩了，但是性能分仍然会折扣5分。
