### ISSUE TITLE
HW2交错代码了怎么办

### ISSUE THREAD

**Issue by sulz33** [multicoresysu/multicore_sysu_slides#44]
第二次成绩，看到成绩只有28分，说是因为结果是全零，去查看了一下邮件记录，发现上次好像是慌慌张张交错了代码，把正确的代码发到邮箱了，想问一下TA成绩还有救吗QAQ

**Comment by williamSYSU** [comment]
成绩已经更新，但是复查后分数会相应折扣5分。
