### ISSUE TITLE
作业2成绩问题

### ISSUE THREAD

**Issue by RyanLiu2015** [multicoresysu/multicore_sysu_slides#45]
TA你好，我是16339028刘远，hw2作业我在提交压缩包时由于疏忽，提交了不正确格式的压缩包，导致成绩表中未显示我的名字。已使用正确的格式重新发送邮件，所有代码均未改动，请您评成绩。已确保在集群能够解压运行。附作业截止日期前发送邮件的截图
![作业2邮箱发送记录](https://user-images.githubusercontent.com/25746588/59561884-dadd4700-9057-11e9-9ee2-0f176aee8554.png)

**Comment by williamSYSU** [comment]
不好意思，批改的时候漏掉了，成绩已经更新。
