### ISSUE TITLE
作业二成绩疑问

### ISSUE THREAD

**Issue by xihuai18** [multicoresysu/multicore_sysu_slides#46]
助教您好！我叫王锡淮，学号是16337236，我在提交时交了多次，最后一次是
![image](https://user-images.githubusercontent.com/23721828/59562799-9a83c600-9063-11e9-9087-6b86fcd11c1c.png)
请问您是否使用的这一份代码

以及请问您测试时使用的卷积核大小是多少？我用s=1、s=2测试时的结果如下：
![image](https://user-images.githubusercontent.com/23721828/59562813-c0a96600-9063-11e9-840d-11aa21b0ff21.png)

**Comment by xihuai18** [comment]
我的问题是正确性只对了一千多个数字，但是我自己测试的时候能对9800多个

**Comment by xihuai18** [comment]
不好意思，我发现问题了，我交了这几次都没有更新附件，请问能再交一次补救吗？我有文件的时间戳证明这真的是ddl之前写好的。

**Comment by williamSYSU** [comment]
成绩已经更新，但是复查后分数会相应折扣5分。
