### ISSUE TITLE
作业二成绩问题

### ISSUE THREAD

**Issue by SDCS-Zyx** [multicoresysu/multicore_sysu_slides#47]
TA你好，我是张奕勋（学号16337314），作业二提交因为编码问题出现编译错误。我检查后发现是添加注释后系统自动修改了编码格式，向老师询问后允许重新提交。我重新提交版本的代码仅修改了注释部分，其他代码没有更改，请重新评成绩。

**Comment by williamSYSU** [comment]
成绩已经更新，但是复查后分数会相应折扣5分。
