### ISSUE TITLE
作业二成绩问题

### ISSUE THREAD

**Issue by xfdj** [multicoresysu/multicore_sysu_slides#49]
TA好，我是黄子聪（16337101），作业结果说我是

运行出错，Error:   hw2_cuda.cu:110, code:2, reason: out of memory

我自己在集群上按照正常流程测试是可以出结果的，并没有出现内存问题，有可能是当时TA测试的时候集群上正好有其它程序占用资源导致，希望TA能够重新进行测试，谢谢。

**Comment by williamSYSU** [comment]
复查后程序运行结果正确，成绩已经更新。
