### ISSUE TITLE
作业三示例代码

### ISSUE THREAD

**Issue by xihuai18** [multicoresysu/multicore_sysu_slides#51]
![image](https://user-images.githubusercontent.com/23721828/59902580-367d4b00-9431-11e9-96a3-98eecc69fd49.png)

这里应该是 arg!=3
然后test.sh里面应该也是忽略了有两个命令行参数这件事。

**Comment by williamSYSU** [comment]
感谢提醒，代码中已经将输出文件的文件名默认设置为`output.bin`。

**Comment by xihuai18** [comment]
![image](https://user-images.githubusercontent.com/23721828/59903639-1602c000-9434-11e9-81e2-2c02274f8874.png)
师兄，还有一个问题，如果测试10000个数，Thrust库和STL库的计时结果如上，我们大多数人写出来的可能还没有串行快。
1000000个数的结果如下
![image](https://user-images.githubusercontent.com/23721828/59903912-ca044b00-9434-11e9-9eb4-691c9f1c291c.png)
10000000个数的结果如下
![image](https://user-images.githubusercontent.com/23721828/59903944-e30cfc00-9434-11e9-96d6-71e2c6363f7a.png)
100000000个数的结果如下
![image](https://user-images.githubusercontent.com/23721828/59904003-0637ab80-9435-11e9-8d7d-c3525e10b9cf.png)
我觉得测试数据至少要10^7个会比较好。

**Comment by Jhhhha** [comment]
同意🙆‍♂️

**Comment by williamSYSU** [comment]
感谢你的反馈，GitHub上放出的`data.bin`中10^4个数据只用来测试，真正在性能测试的时候会重新生成10^8个数来进行性能测试，所以请放心。
