### ISSUE TITLE
关于报告评分的疑问

### ISSUE THREAD

**Issue by Jhhhha** [multicoresysu/multicore_sysu_slides#56]
助教好，我的学号是16337303，姓名是张家豪，不知道助教方不方便告诉我一下为什么我报告二的评分会比报告一评分还低，因为个人感觉报告二的内容可能会被报告一更丰富。现在准备交报告三了，但是不太知道为什么跟第一次比扣了6分，所以想了解一下，然后把报告三改的更好一些，以免扣太多分。

**Comment by williamSYSU** [comment]
在实验报告中阐述程序逻辑部分可以更详细些，性能优化和参数讨论部分完成都比较好。
