### ISSUE TITLE
关于作业三“程序没反应”

### ISSUE THREAD

**Issue by ghost** [multicoresysu/multicore_sysu_slides#59]
TA你好，我的作业三评分显示“程序没反应”，可能是性能太差(平方复杂度)以至于在一定时间内没有结果输出。
这是样例测试的结果（10,000）：
![a](https://user-images.githubusercontent.com/28523660/61179195-82866e80-a630-11e9-822a-f9444c7c12a0.PNG)
可以看到程序有输出
我在报告中测试过100,000个数值排序，结果如下
![b](https://user-images.githubusercontent.com/28523660/61179224-06d8f180-a631-11e9-8092-1684e1ed76b7.PNG)

**Comment by ghost** [comment]
16337153 凌笑铃

**Comment by ghost** [comment]
根据10w数据量所需要的时间推算，100w数据排序大概需要10,0000ms

**Comment by williamSYSU** [comment]
成绩已经更新。
