### ISSUE TITLE
请问代码扣2分是什么原因

### ISSUE THREAD

**Issue by gimpong** [multicoresysu/multicore_sysu_slides#60]
老师及助教师兄们好！

        我是16337232王锦鹏，我的代码又被扣了两分。但是我自己不知道为什么，自我复查之后我认为我的代码格式达到要求的样式。因此怀着诚恳，在此诚心求问，是我何处做的不够规范？

期盼您们的回复，祝您们生活与工作顺利！
学生：王锦鹏

**Comment by williamSYSU** [comment]
你说的是作业几？

**Comment by xihuai18** [comment]
助教您好，我也想问我作业3的代码分为什么扣了4分
我叫王锡淮，学号是16337236

**Comment by JPGene** [comment]
作业3，师兄

**Comment by gimpong** [comment]
> 你说的是作业几？
作业3，师兄

**Comment by why116600** [comment]
注释是评分的重要指标，你目前提交的程序只有函数开头的注释，代码行间基本没有注释，所以不能给满分

**Comment by why116600** [comment]
> 助教您好，我也想问我作业3的代码分为什么扣了4分
> 我叫王锡淮，学号是16337236

你的程序完全没有注释

**Comment by xihuai18** [comment]
> > 助教您好，我也想问我作业3的代码分为什么扣了4分
> > 我叫王锡淮，学号是16337236
> 
> 你的程序完全没有注释

助教您是不是只看了我的主文件，我的主要功能完成在了其他文件里

**Comment by ghost** [comment]
> 注释是评分的重要指标，你目前提交的程序只有函数开头的注释，代码行间基本没有注释，所以不能给满分

师兄您好！感谢您的快速回复。
我再次Review我的代码，我仍然对扣分的原因感到困惑。由于本次实验比较特殊，需要有多个组件(我用Radix Sort，写了双调排序的另谈)。为了保持Project整体上的结构规范，我将组件的功能放置`util.h`文件中，在该文件中，由于需要涉及具体的逻辑，我**不仅**按照规范要求，在函数头和代码文件首部添加了函数或者文件的说明，**还在代码行间进行了注释**。
而在主文件`cuda_hw3.cu`中，其实需要学生自己填充的部分，**只有**一个函数（其他都是给定的模板）。我觉得读者都很容易理解代码的意思。原因：
1. 长度短；
2. 逻辑都比较简单，做什么其实在函数头已经写了，算法代码就那么几行，每一行都写注释有点牵强了；
3. 这部分代码有大量`cudaMalloc`这类非算法逻辑的代码占位。属于不需要行注释的情况）。
并且辅助以清晰的变量名和API名，要做什么动作不难看出。

学生不易，每一分都付出了精力，能争取的则需要争取，请您宽容并希望您为我添上这令人困惑的两分，感谢您！

祝老师生活和工作顺利，祝助教师兄们生活和学业顺利！
学生：王锦鹏

**Comment by why116600** [comment]
你的主程序里面仍然有两个与业务相关的函数kernel和radixSort，这俩的行间完全没注释，因此最多加1分

**Comment by why116600** [comment]
> > > 助教您好，我也想问我作业3的代码分为什么扣了4分
> > > 我叫王锡淮，学号是16337236
> > 
> > 
> > 你的程序完全没有注释
> 
> 助教您是不是只看了我的主文件，我的主要功能完成在了其他文件里

主文件作为你程序的门面，是我们重点评判的地方，如果你的主要程序在其他文件，你的主程序最好能有注释强调一下。现在看你其他程序注释比较详细，就改为只扣1分吧
