### ISSUE TITLE
作业三备注“无核函数”

### ISSUE THREAD

**Issue by wind2009** [multicoresysu/multicore_sysu_slides#61]
情况：备注显示我没有核函数，但是我的代码在285行进入_cuda_sort_，并在256行执行了_kernel_。在测试的时候核函数也可以正常执行。
这次的实验有很多同学的备注都是无核函数，也许是测试的时候集群gpu被占用的问题，希望可以重新跑一次。

**Comment by williamSYSU** [comment]
应该是当时集群上显卡资源不足造成的，现在已经重新测试并更新成绩了。
