### ISSUE TITLE
作业三“输出全错”

### ISSUE THREAD

**Issue by XA-kirino** [multicoresysu/multicore_sysu_slides#62]
16337331 钟哲灏
成绩表里显示作业三输出全错，然而采用样例测试能够正确输出，并且采用自己随机生成的100M的UINT数据集也能够正确输出，其他同学也遇到了同样的问题，希望TA能够重新提供测试集给我们自己测试。

**Comment by XA-kirino** [comment]
我采用的是双调排序，本地测试采用集群上的cudaDevice（2）

**Comment by williamSYSU** [comment]
成绩已经更新了。
