### ISSUE TITLE
作业三备注“无核函数”问题

### ISSUE THREAD

**Issue by RyanLiu2015** [multicoresysu/multicore_sysu_slides#64]
学号：16339028    姓名：刘远
作业3成绩备注中显示无核函数。
然而我的代码中的有核函数kernel，由主函数直接调用。提交之前已经在集群测试无误。
附截图：
![6XN9_9UV3EUKH7M12KZOD5U](https://user-images.githubusercontent.com/25746588/61182916-c5fece00-a66c-11e9-843a-181fdf32b169.png)

**Comment by williamSYSU** [comment]
应该是当时集群上显卡资源不足造成的，现在已经重新测试并更新成绩了。
