### ISSUE TITLE
关于作业三"程序没反应"

### ISSUE THREAD

**Issue by wanghanggithub** [multicoresysu/multicore_sysu_slides#65]
TA您好，我的作业三显示"程序无反应"，我在本地进行了多次测试，结果均是正确的，可能原因是在测试我程序时有其他程序在运行导致我无法申请到显存以致我的程序被kill，我在这里请求TA重新测试一下我的程序，谢谢！16343051 刘鹏宇

**Comment by williamSYSU** [comment]
应该是当时集群上显卡资源不足造成的，现在已经重新测试并更新成绩了。
