### ISSUE TITLE
关于作业3“无核函数”的问题

### ISSUE THREAD

**Issue by SmileDreamer** [multicoresysu/multicore_sysu_slides#66]
TA学长/老师：
您好！我是16337319 赵彬琦
我的作业三显示"无核函数"，但我在代码25行确有核函数kernel，并在第57行调用了该核函数。
![屏幕快照 2019-07-15 08 56 31](https://user-images.githubusercontent.com/38682971/61191676-c08e9b80-a6df-11e9-916a-98f6afcbb2db.png)
![屏幕快照 2019-07-15 08 56 11](https://user-images.githubusercontent.com/38682971/61191677-c08e9b80-a6df-11e9-89b7-566805720e3e.png)

同时，我集群上进行了多次测试，结果正确。
![截图](https://user-images.githubusercontent.com/38682971/61191715-372b9900-a6e0-11e9-8463-62d4e467057e.png)

可能原因是在测试我程序时有其他程序在运行导致我无法申请到显存以致我的程序被kill，我在这里申请TA重新测试一下我的程序，谢谢！

**Comment by williamSYSU** [comment]
应该是当时集群上显卡资源不足造成的，现在已经重新测试并更新成绩了。
