### ISSUE TITLE
作业三“输出全错”

### ISSUE THREAD

**Issue by zqfxx1** [multicoresysu/multicore_sysu_slides#67]
TA好，我检查我的作业三修改了代码，已经重新提交跟新的作业发送至邮箱了
16337308-zhangqifan

**Comment by williamSYSU** [comment]
重新测试了你的代码，报`Error: Application received signal 139`这个错误。

**Comment by zqfxx1** [comment]
您好，我在本机测试cuda时候是正确的，请问我能晚点补一个本机测试的截图给您吗
我个人在集群上测试也能成功编译运行




------------------ 原始邮件 ------------------
发件人: "WilliamLam"<notifications@github.com>; 
发送时间: 2019年7月15日(星期一) 中午12:41
收件人: "multicoresysu/multicore_sysu_slides"<multicore_sysu_slides@noreply.github.com>; 
抄送: "905935657"<905935657@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [multicoresysu/multicore_sysu_slides] 作业三“输出全错” (#67)




重新测试了你的代码，报Error: Application received signal 139这个错误。

**Comment by OnlyCaptain** [comment]
助教你好，我昨天下午发了第二版本的代码
![image](https://user-images.githubusercontent.com/28449586/61279284-65949b80-a7e8-11e9-9dd2-196130aae60d.png)
因为没能赶上TA第一次重测，请求TA再测试一次
@williamSYSU

**Comment by williamSYSU** [comment]
已重新测试并更新了成绩。
