### ISSUE TITLE
请求重测作业3

### ISSUE THREAD

**Issue by xfdj** [multicoresysu/multicore_sysu_slides#69]
助教好：
我是黄子聪（16337101），我自己在集群上测试过，并没有出现报告中出现的问题，答案也正确，请助教重新测试，谢谢。
![image](https://user-images.githubusercontent.com/38575841/61205866-bc846d00-a723-11e9-8428-ab11ac295619.png)

**Comment by williamSYSU** [comment]
已重新测试并更新了成绩。
