### ISSUE TITLE
第一次作业成绩单中没有找到我的成绩

### ISSUE THREAD

**Issue by hongwen000** [multicoresysu/multicore_sysu_slides#7]
老师您好，我的学号是15323032，对应md5哈希值为09f300dec4b3499a260b65070ede68e4
。第一次作业成绩单中没有找到我的成绩。以下是我4月8日提交作业的邮件截图。麻烦您让助教师兄检查一下是不是忘记批改了我的作业？
![image](https://user-images.githubusercontent.com/25456415/57746726-10afa880-7705-11e9-81e4-c3112e5a3edc.png)

**Comment by williamSYSU** [comment]
很抱歉漏改了你的作业，成绩已更新。
