### ISSUE TITLE
请求作业3重测

### ISSUE THREAD

**Issue by Wayne-Mai** [multicoresysu/multicore_sysu_slides#72]
作业三成绩上显示：`Error:   Application returned non-zero code -1--`。
但是本地运行未发现错误，因此请求TA重测。
16337179——麦金杰
![image](https://user-images.githubusercontent.com/29971580/61431036-a8787f80-a95e-11e9-87ce-5b4acc2ada6a.png)

**Comment by williamSYSU** [comment]
已经重新测试过了，没有问题，成绩已经更新了。
