### ISSUE TITLE
作业三，CUDA性能一项空缺

### ISSUE THREAD

**Issue by kokifish** [multicoresysu/multicore_sysu_slides#75]
作业三正确性符合要求，但CUDA性能这一项上空缺，而性能分为10分，没有备注。在我使用10^8的数据进行测试时未发现问题，烦请TA复查并给予测试反馈。谢谢！

学号：16337087

**Comment by williamSYSU** [comment]
抱歉，登记成绩的时候漏掉了，现在成绩已经更新了。
