### ISSUE TITLE
作业一

### ISSUE THREAD

**Issue by xihuai18** [multicoresysu/multicore_sysu_slides#8]
请问助教能不能提供一个联系方式，我的输出多了换行（因为我是对照ppt的，抱歉），这导致了我的答案错误，能否宽容一下。

**Comment by williamSYSU** [comment]
278976237@qq.com，把你的姓名和学号发给我，我重新看一下你的程序。

**Comment by yxsysu** [comment]
师兄，仍有同学存在两个成绩 学号 16337210，请师兄再核实一下 谢谢师兄

**Comment by williamSYSU** [comment]
成绩已经更新。
