### ISSUE TITLE
作业一成绩问题

### ISSUE THREAD

**Issue by Jhhhha** [multicoresysu/multicore_sysu_slides#9]
师兄，第一次作业总分那一列好像加错了，虽然计算的式子是对的，但有些行手动算的结果不对，我的成绩是第四十行好像也不对

**Comment by Jhhhha** [comment]
好像应该是110，但是变成了90

**Comment by xihuai18** [comment]
![image](https://user-images.githubusercontent.com/23721828/57757738-b7f20700-7728-11e9-81ae-8105ea9c1ac9.png)
公式是对的，但是有些单元格是字符串，不参与求和。

**Comment by williamSYSU** [comment]
感谢提醒，已经重新计算。
